# Generated by Django 4.0.1 on 2022-06-27 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_alter_table_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numero correct', regex='^[0-9]*$')]),
        ),
    ]
