# Generated by Django 4.0.1 on 2022-06-27 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_alter_client_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='entrer un nombre valide', regex='^(1[1-9]|2[1-2,4,7,8]|3[1-5]|3[7-8]|4[1-9]|5[1,3-5]|6[1-9]|7[1,3,4,5,7,9]|8[1-9]|9[1-9]){1}[0-9]{8,9}$')]),
        ),
    ]
