# Generated by Django 4.1.5 on 2023-01-31 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_alter_client_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='entrer un nombre valide', regex='^(1[1-9]|2[1-2,4,7,8]|3[1-5]|3[7-8]|4[1-9]|5[1,3-5]|6[1-9]|7[1,3,4,5,7,9]|8[1-9]|9[1-9]){1}[0-9]{8,9}$')]),
        ),
    ]
