# Generated by Django 4.1.7 on 2023-03-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0011_alter_client_id_alter_reservation_salle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_salle',
            name='type_evenement',
            field=models.CharField(choices=[('diner_vip', 'diner_vip'), ('diner_Normal', 'diner_Normal'), ('autre', 'autre')], default='autre', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation_table',
            name='nombre_place',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation_table',
            name='type_evenement',
            field=models.CharField(choices=[('diner_vip', 'diner_vip'), ('diner_Normal', 'diner_Normal'), ('autre', 'autre')], default='autre', max_length=50),
        ),
    ]
