# Generated by Django 4.1.7 on 2023-03-25 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0012_reservation_salle_type_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_table',
            name='nombre_place',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
