# Generated by Django 4.1.7 on 2023-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0014_alter_reservation_salle_type_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_table',
            name='type_evenement',
            field=models.CharField(choices=[('diner_vip', 'diner_vip'), ('diner_Normal', 'diner_Normal'), ('Conference', 'Conference'), ('Festival', 'Festival'), ('Mariage', 'Mariage'), ('autre', 'autre')], max_length=50),
        ),
    ]
