# Generated by Django 4.1.7 on 2023-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0015_alter_reservation_table_type_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_salle',
            name='nombre_table',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='reservation_salle',
            name='type_evenement',
            field=models.CharField(choices=[('diner_vip', 'diner_vip'), ('diner_Normal', 'diner_Normal'), ('Conference', 'Conference'), ('Festival', 'Festival'), ('Mariage', 'Mariage'), ('autre', 'autre')], max_length=50),
        ),
    ]
